### ISSUE TITLE
[Help] Miners can't connect due to Stratum client disconnected: "Not Connected!"

### ISSUE THREAD

**Issue by xD0135** [bonesoul/CoiniumServ#851]
I downloaded, compiled and configured CoiniumServ yesterday and when I try to connect my miner to the pool on my network:

```
sgminer -o stratum+tcp://10.10.10.136:4033 -u WALLET -p 1 -k scrypt
```

 I get the following in logs/debug.log:

```
10/09/2017 13:10:12 -07:00 [Debug] [StratumServer] [Litecoin] Stratum client connected: "10.10.10.142:52007"
10/09/2017 13:10:28 -07:00 [Debug] [StratumServer] [Litecoin] Stratum client disconnected: "Not Connected!"
10/09/2017 13:10:28 -07:00 [Debug] [StratumServer] [Litecoin] Stratum client connected: "10.10.10.142:52020"
```

I can confirm that the port is open and working by executing the following command from the same machine as I run the miner:

```
$ telnet 10.10.10.136 4033
Trying 10.10.10.136...
Connected to 10.10.10.136.
Escape character is '^]'.
```

Any help is highly appreciated.

**Comment by regtable** [comment]
Stratum client connected: "ip.xx.xxx.xxx:44680"
Authenticated miner: 240946301422927882.1 [ip.xxx.xxx.xxx:44680]
Stratum client disconnected: "Not Connected!"
for some users others are fine.

**Comment by nghieppv** [comment]
same issus. help me please

**Comment by kreiseder** [comment]
Hi Guys, 
which VPS servers (Providers) are you using? 
i experienced the same problem.

**Comment by regtable** [comment]
I use my own. I fixed my issue by adding coinbase values and or other block template required things. It's only happened with 1 coin but it may happen with others

**Comment by regtable** [comment]
Are you using mpos layer and shared accounts?

**Comment by kreiseder** [comment]
on my previous VPS providor i could not make it work. 
So i just tried another VPS hoster. Now i can successfully connect from remote
with cpuminer.

i just use litecoin daemon for testing now and coiniumserv 

you?

**Comment by xD0135** [comment]
I gave up on this project and switched to YiiMP, hence closing the issue.

**Comment by lahendrix** [comment]
@cycleworm What previous VPS hoster could you not get to work? Was it Microsoft Azure? I've got a linux VM in Azure and I'm experiencing the exact same thing. I'm using the digibyte daemon with CoiniumServ and I can confirm through telnet the connection is open, but my miner still can't connect. So I was considering trying AWS
